apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-consumer
  labels:
    app: booking-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-consumer
  template:
    metadata:
      labels:
        app: booking-consumer
    spec:
      containers:
      - name: booking-consumer
        image: "{{IMAGE}}" # To be replaced in CI/CD environment
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq.broker.svc.cluster.local"

