apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-producer
  labels:
    app: booking-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-producer
  template:
    metadata:
      labels:
        app: booking-producer
    spec:
      containers:
      - name: booking-producer
        image: "{{IMAGE}}" # To be replaced in CI/CD environment
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /swagger-ui/index.html
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /swagger-ui/index.html
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: SPRING_MAIN_ALLOWBEANDEFINITIONOVERRIDING
          value: "{{SPRING_MAIN_ALLOWBEANDEFINITIONOVERRIDING}}"
        - name: SPRING_RABBITMQ_HOST
          value: "{{SPRING_RABBITMQ_HOST}}"
        - name: SPRING_RABBITMQ_PORT
          value: "{{SPRING_RABBITMQ_PORT}}"
        - name: SPRING_RABBITMQ_USERNAME
          value: "{{SPRING_RABBITMQ_USERNAME}}"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "{{SPRING_RABBITMQ_PASSWORD}}"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-producer
spec:
  type: NodePort
  selector:
    app: booking-producer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
