apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-consumer
  labels:
    app: booking-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-consumer
  template:
    metadata:
      labels:
        app: booking-consumer
    spec:
      containers:
      - name: booking-consumer
        image: "{{IMAGE}}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "pgrep -f 'java -jar booking-consumer-service.jar'"
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "{{SPRING_RABBITMQ_HOST}}"
        - name: SPRING_RABBITMQ_PORT
          value: "{{SPRING_RABBITMQ_PORT}}"
        - name: SPRING_RABBITMQ_USERNAME
          value: "{{SPRING_RABBITMQ_USERNAME}}"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "{{SPRING_RABBITMQ_PASSWORD}}"
        - name: SPRING_RABBITMQ_LISTENER_DIRECT_DEFAULTREQUEUEREJECTED
          value: "{{SPRING_RABBITMQ_LISTENER_DIRECT_DEFAULTREQUEUEREJECTED}}"
        - name: SPRING_DATASOURCE_URL
          value: "{{SPRING_DATASOURCE_URL}}"
        - name: SPRING_DATASOURCE_DRIVERCLASSNAME
          value: "{{SPRING_DATASOURCE_DRIVERCLASSNAME}}"
        - name: SPRING_DATASOURCE_USERNAME
          value: "{{SPRING_DATASOURCE_USERNAME}}"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "{{SPRING_DATASOURCE_PASSWORD}}"
        - name: SPRING_JPA_DATABASEPLATFORM
          value: "{{SPRING_JPA_DATABASEPLATFORM}}"
        - name: SPRING_JPA_HIBERNATE_DDLAUTO
          value: "{{SPRING_JPA_HIBERNATE_DDLAUTO}}"
        - name: SPRING_JPA_GENERATEDDL
          value: "{{SPRING_JPA_GENERATEDDL}}"
