apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-producer
  labels:
    app: booking-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-producer
  template:
    metadata:
      labels:
        app: booking-producer
    spec:
      containers:
      - name: booking-producer
        image: "{{IMAGE}}" # To be replaced in CI/CD environment
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-producer
spec:
  type: NodePort
  selector:
    app: booking-producer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
