name: CD-eCABS

on:
  push:
    branches:
    - master
    # An alternative approach could 
    # be to trigger this workflow on release tags

jobs:
  mvn-build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      
  docker-build:
    needs: mvn-build
    runs-on: ubuntu-latest
    env:
      GHCR: ghcr.io/samuelagm/
    strategy:
        matrix:
          project: [booking-consumer-service, booking-producer-service]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
            cd ${{ matrix.project }}
            docker build -t ${{ env.GHCR }}${{ matrix.project }}:${{ github.sha }} -t ${{ env.GHCR }}${{ matrix.project }}:latest .
            docker push ${{ env.GHCR }}${{ matrix.project }}:${{ github.sha }}
            docker push ${{ env.GHCR }}${{ matrix.project }}:latest